const recoilMoves = [
  "bravebird",
  "doubleedge",
  "flareblitz",
  "headcharge",
  "headsmash",
  "highjumpkick",
  "jumpkick",
  "lightofruin",
  "mindblown",
  "shadowend",
  "shadowrush",
  "steelbeam",
  "struggle",
  "submission",
  "takedown",
  "volttackle",
  "wildcharge",
  "woodhammer",
];

const confusionMoves = [
  "Chatter",
  "Confuse Ray",
  "Confusion",
  "Dizzy Punch",
  "Dynamic Punch",
  "Flatter",
  "Hurricane",
  "Outrage",
  "Petal Dance",
  "Psybeam",
  "Rock Climb",
  "Secret Power",
  "Shadow Panic",
  "Signal Beam",
  "Strange Steam",
  "Supersonic",
  "Swagger",
  "Sweet Kiss",
  "Teeter Dance",
  "Thrash",
  "Water Pulse",
];

const toxicMoves = [
  "Baneful Bunker",
  "Cross Poison",
  "Dire Claw",
  "Fling",
  "Gunk Shot",
  "Poison Fang",
  "Poison Gas",
  "Poison Jab",
  "Poison Powder",
  "Poison Sting",
  "Poison Tail",
  "Psycho Shift",
  "Secret Power",
  "Shell Side Arm",
  "Sludge",
  "Sludge Bomb",
  "Sludge Wave",
  "Smog",
  "Toxic",
  "Toxic Thread",
  "Twineedle",
];

const burnMoves = [
  "Beak Blast",
  "Blaze Kick",
  "Blue Flare",
  "Burning Jealousy",
  "Ember",
  "Fire Blast",
  "Fire Fang",
  "Fire Punch",
  "Flame Wheel",
  "Flamethrower",
  "Flare Blitz",
  "Fling",
  "Heat Wave",
  "Ice Burn",
  "Inferno",
  "Lava Plume",
  "Psycho Shift",
  "Pyro Ball",
  "Sacred Fire",
  "Scald",
  "Scorching Sands",
  "Searing Shot",
  "Secret Power",
  "Shadow Fire",
  "Sizzly Slide",
  "Steam Eruption",
  "Tri Attack",
  "Will-O-Wisp",
];

const paraMoves = [
  "Body Slam",
  "Bolt Strike",
  "Bounce",
  "Buzzy Buzz",
  "Dire Claw",
  "Discharge",
  "Dragon Breath",
  "Fling",
  "Force Palm",
  "Freeze Shock",
  "G-Max Befuddle",
  "G-Max Stun Shock",
  "G-Max Volt Crash",
  "Glare",
  "Lick",
  "Nuzzle",
  "Psycho Shift",
  "Secret Power",
  "Shadow Bolt",
  "Spark",
  "Splishy Splash",
  "Stoked Sparksurfer",
  "Stun Spore",
  "Thunder",
  "Thunder Fang",
  "Thunder Punch",
  "Thunder Shock",
  "Thunder Wave",
  "Thunderbolt",
  "Tri Attack",
  "Volt Tackle",
  "Zap Cannon",
];

const freezeMoves = [
  "Blizzard",
  "Freeze-Dry",
  "Freezing Glare",
  "Ice Beam",
  "Ice Fang",
  "Ice Punch",
  "Powder Snow",
  "Secret Power",
  "Shadow Chill",
  "Tri Attack",
];

const sleepMoves = [
  "Dark Void",
  "G-Max Befuddle",
  "G-Max Snooze",
  "Grass Whistle",
  "Hypnosis",
  "Lovely Kiss",
  "Psycho Shift",
  "Relic Song",
  "Rest",
  "Secret Power",
  "Sing",
  "Sleep Powder",
  "Spore",
  "Yawn",
];

const statusMoves = [
  ...toxicMoves,
  ...burnMoves,
  ...paraMoves,
  ...sleepMoves,
  ...freezeMoves,
];

const statusAbility = [
  "Poison Point",
  "Poison Touch",
  "Flame Body",
  "Effect Spore",
  "Static",
];

const hazardMoves = [
  "Stealth Rock",
  "Spikes",
  "G-Max Volcalith",
  "G-Max Vineslash",
  "G-Max Wildfire",
  "G-Max Cannonade",
  "G-Max Vine Lash",
  "G-Max Centiferno",
  "G-Max Sandblast",
  "Sticky Web",
  "Court Change",
];

const misnomers = [
  "Gastrodon",
  "Florges",
  "Toxtricity",
  "Vivillon",
  "Silvally-Bug",
  "Silvally-Dark",
  "Silvally-Dragon",
  "Silvally-Electric",
  "Silvally-Fairy",
  "Silvally-Fighting",
  "Silvally-Fire",
  "Silvally-Flying",
  "Silvally-Ghost",
  "Silvally-Grass",
  "Silvally-Ground",
  "Silvally-Ice",
  "Silvally-Normal",
  "Silvally-Poison",
  "Silvally-Psychic",
  "Silvally-Rock",
  "Silvally-Steel",
  "Silvally-Water",
  "Silvally-*",
  "Pumpkaboo",
  "Pumpkaboo-Small",
  "Gourgeist",
  "Gourgeist-Super",
  "Oricorio",
  "Arceus-*",
  "Keldeo",
  "Urshifu-*",
  "Genesect-Burn",
  "Genesect-Chill",
  "Genesect-Douse",
  "Genesect-Shock",
  "Mimikyu-Busted",
  "Alcremie-Vanilla-Cream",
  "Alcremie-Caramel-Swirl",
  "Alcremie-Ruby-Cream",
  "Alcremie-Ruby-Swirl",
  "Alcremie-Matcha-Cream",
  "Alcremie-Lemon-Cream",
  "Alcremie-Salted-Cream",
  "Alcremie-Mint-Cream",
  "Alcremie-Rainbow-Swirl",
  "Indeedee-F",
  "Zarude-Dada",
  "Palafin-Hero",
  "Minior-Red",
  "Minior-Orange",
  "Minior-Yellow",
  "Minior-Green",
  "Minior-Blue",
  "Minior-Indigo",
  "Minior-Violet",
  "Maushold-Four",
  "Sinistcha-Masterpiece",
  "Dudunsparce-Three-Segment",
];

export const consts = {
  recoilMoves,
  confusionMoves,
  statusMoves,
  statusAbility,
  hazardMoves,
  misnomers,
};
